### ISSUE TITLE
Testing for zero length more elegant than deepEqual with empty

### ISSUE THREAD

**Issue by des-des** [FACN1/week2-Khan-ElBash#33]
https://github.com/FACN1/week2-Khan-ElBash/blob/master/Test/test.js#L41
`assert.equal(arr.length, 0)` nicer than `assert.deepEqual(arr, [])`

**Comment by mattlub** [comment]
thanks. appreciate any help in the quest for elegance.

**Comment by des-des** [comment]
:+1:
